git:
  submodules: false    
os: linux
dist: xenial
services: docker
env: DOCKER_IMAGE=zhaofengshu33/mini-latex:v1
script:
  - docker run -v `pwd`:/code $DOCKER_IMAGE /bin/sh -c 'cd /code; make'
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - build/trivial_solution.pdf  
    - build/clustering.pdf
    - build/main.pdf
    - build/pmf.pdf
    - build/psp_improved.pdf
  skip_cleanup: true
  on:
    tags: true