selected_scheme scheme-basic
collection-fontsrecommended 1
collection-latex 1
collection-xetex 1
tlpdbopt_install_docfiles 0
tlpdbopt_install_srcfiles 0
TEXDIR /tmp/texlive
TEXMFLOCAL /tmp/texlive/texmf-local
TEXMFSYSCONFIG /tmp/texlive/texmf-config
TEXMFSYSVAR /tmp/texlive/texmf-var
